### PR TITLE
Feature Request: Find the nth root of a number

### LINKED ISSUE #41: Feature Request: Find the nth root of a number
A function to find the nth root of a number

### PR DESCRIPTION
**Pull request by SinghalChinmay**
Fixes #41

# Mathician Pull Requests

# Changes Description
Replace this text with a clear description of the changes you've made.
The changes include:
- Adding of a function which calculates the nth root a number.
- Formatted the files.

- [x] I have reviewed my changes and if it is related with programming, it has been tested.
- [x] I understand that these changes will become under the property of Mathician if merged and I agree to let the changes be used in Mathician's repository.

### CODE REVIEW

**Comment by SinghalChinmay** [comment]
Shall I add an example about this in the `examples` folder?

**Comment by ArjunSharda** [comment]
Sure!

**Comment by SinghalChinmay** [comment]
Done!

**Review by ArjunSharda — APPROVED** [review]
Will merge this later today, LGTM!

**Pull request merged**
